version: '3.8'

services:
  assessment-service:
    image: mrksdh/assessment
    ports:
      - "8080:8080"
    networks:
      - app-network

  cloud-calculator:
    build: .
    ports:
      - "8081:8080"  # ich muss es woanders mappen sonst geht es nicht
    depends_on:
      - assessment-service
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
