name: HTTP Status Check
on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        run: docker-compose up --build -d

      - name: Run Tests
        run: docker-compose exec cloud-calculator curl -X GET http://localhost:8081/v1/result

      - name: Tear down Docker Compose
        run: docker-compose down
