name: HTTP Status Check
on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose
        run: docker-compose up --build -d

      - name: Run Tests
        run: |
          curl http://localhost:8080/v1/dataset
          curl http://localhost:8081/v1/result

      - name: Shutdown Docker Compose
        run: docker-compose down
      
