name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  system-assessment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Run with Docker Compose
        run: |
          docker-compose up -d --build || exit 1

      - name: Wait for Services to be Ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/v1/dataset; then
              echo "Services are ready!"
              break
            fi
            echo "Waiting for services..."
            sleep 3
          done || exit 1

      - name: Check Logs for Assessment Service
        run: |
          echo "Logs from assessment service:"
          docker-compose logs assessment-service | tee assessment_logs.txt  # Protokolliere die Logs in eine Datei

      - name: Check Logs for Cloud Calculator
        run: |
          echo "Logs from cloud-calculator:"
          docker-compose logs cloud-calculator | tee local_logs.txt  # Protokolliere die Logs in eine Datei

      - name: Verify Success in Logs
        run: |
          if grep -q '"code":200,"message":"well done!"' local_logs.txt; then
              echo "Success: The message '200, well done!' was found!"
          else
              echo "Error: The message '200, well done!' was not found!"
              exit 1
          fi

      - name: Verify Containers are Running
        run: docker-compose ps

      - name: Cleanup
        run: |
          docker-compose down || exit 0
