name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and Run Docker Compose
      run: docker-compose up --build -d
      working-directory: ./CloudCalculator

    - name: Run Tests
      run: docker-compose run --rm cloud-calculator curl -X GET http://assessment-service:8081/v1/result
      working-directory: ./CloudCalculator

    - name: Tear down Docker Compose
      run: docker-compose down
      working-directory: ./CloudCalculator
